CREATE TABLE [dbo].[CART_DETAIL] (
    [ID_ACCOUNT]    INT NOT NULL,
    [ID_PRODUCT]    INT NOT NULL,
    [CART_PRICE]    INT NULL,
    [CART_S]        INT DEFAULT ((0)) NULL,
    [CART_M]        INT DEFAULT ((0)) NULL,
    [CART_L]        INT DEFAULT ((0)) NULL,
    [CART_XL]       INT DEFAULT ((0)) NULL,
    [CART_XXL]      INT DEFAULT ((0)) NULL,
    [CART_OVERSIZE] INT DEFAULT ((0)) NULL,
    CONSTRAINT [PK_CART] PRIMARY KEY CLUSTERED ([ID_ACCOUNT] ASC, [ID_PRODUCT] ASC),
    CONSTRAINT [FK_CART_IDACC] FOREIGN KEY ([ID_ACCOUNT]) REFERENCES [dbo].[ACCOUNT] ([ID_ACCOUNT]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_CART_IDPRODUCT] FOREIGN KEY ([ID_PRODUCT]) REFERENCES [dbo].[PRODUCT] ([ID_PRODUCT]) ON DELETE CASCADE ON UPDATE CASCADE
);

